apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-pubsub-demo-sa
  namespace: default  # Or your namespace
  annotations:
    iam.gke.io/gcp-service-account: myapp-catalog-subscriber@project-602c1df5-e612-4947-a79.iam.gserviceaccount.com
